
download(){
  wget --no-check-certificate -O "$1" "$2"
}

make_all(){

  if [ "$CC" = "" ] ; then
    export CC="gcc"
  fi

  mkdir -p "$RELEASE_FOLDER"/
  
  PACKNAME="precontainer"
  if [ ! -f "/bin/sh" -a ! -f "$DIR_BUILD/$PACKNAME.built" ]; then\
    mkdir -p "$DIR_BUILD/$PACKNAME"
    cd "$DIR_BUILD/$PACKNAME"

    mkdir -p /alpine-temp
    cd /alpine-temp
    download tmp.tar.gz https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/x86_64/alpine-minirootfs-3.21.2-x86_64.tar.gz
    tar -xzf tmp.tar.gz
    rm tmp.tar.gz
    cd -
    cd /
    yes n | cp -Ri alpine-temp/./ ./
    rm -fR alpine-temp
    cd -

    touch "$DIR_BUILD/$PACKNAME.built"
  fi
  
  PACKNAME="envdep"
  if [ ! -f "$DIR_BUILD/$PACKNAME.done" ]; then

    apk add \
      binutils file \
      gcc g++ \
      libc-dev fortify-headers linux-headers \
      make patch perl make

    touch "$DIR_BUILD/$PACKNAME.done"
  fi

  PACKNAME="busybox"
  cd "$DIR_BUILD"
  if [ ! -f "$DIR_BUILD/$PACKNAME.downloaded" ]; then
    download tmp.zip https://github.com/mirror/busybox/archive/refs/heads/master.zip
    unzip tmp.zip
    rm tmp.zip
    touch "$DIR_BUILD/$PACKNAME.downloaded"
  fi
  cd "$DIR_BUILD/busybox-master"
  if [ ! -f "$DIR_BUILD/$PACKNAME.built" ]; then
    make defconfig
    cp .config .config.auto
    #
    # From musl documentation
    sed -i 's~.*\<CONFIG_EXTRA_COMPAT\>.*~CONFIG_EXTRA_COMPAT=n~' .config
    sed -i 's~.*\<CONFIG_SELINUX\>.*~CONFIG_SELINUX=n~' .config
    sed -i 's~.*\<CONFIG_WERROR\>.*~CONFIG_WERROR=n~' .config
    sed -i 's~.*\<CONFIG_FEATURE_VI_REGEX_SEARCH\>.*~CONFIG_FEATURE_VI_REGEX_SEARCH=n~' .config
    sed -i 's~.*\<CONFIG_PAM\>.*~CONFIG_PAM=n~' .config
    sed -i 's~.*\<CONFIG_FEATURE_INETD_RPC\>.*~CONFIG_FEATURE_INETD_RPC=n~' .config
    sed -i 's~.*\<CONFIG_SELINUXENABLED\>.*~CONFIG_SELINUXENABLED=n~' .config
    sed -i 's~.*\<CONFIG_FEATURE_MOUNT_NFS\>.*~CONFIG_FEATURE_MOUNT_NFS=n~' .config
    sed -i 's~.*\<CONFIG_FEATURE_HAVE_RPC\>.*~CONFIG_FEATURE_HAVE_RPC=n~' .config
    sed -i 's~.*\<CONFIG_FEATURE_SYSTEMD\>.*~CONFIG_FEATURE_SYSTEMD=n~' .config
    #
    # Euristic
    sed -i 's~.*\<CONFIG_DEBUG_SANITIZE\>.*~CONFIG_DEBUG_SANITIZE=n~' .config
    #
    # Enable static
    sed -i 's~.*\<CONFIG_PIE\>.*~CONFIG_PIE=n~' .config # PIE = position independent exectuble, it is not useful for static
    sed -i 's~.*\<CONFIG_STATIC\>.*~CONFIG_STATIC=y~' .config
    sed -i 's~.*\<CONFIG_FEATURE_LIBBUSYBOX_STATIC\>.*~CONFIG_FEATURE_LIBBUSYBOX_STATIC=y~' .config
    sed -i 's~.*\<CONFIG_STATIC_LIBGCC\>.*~CONFIG_STATIC_LIBGCC=y~' .config
    #
    # Enable standalone # TODO : test PREFER_APPLETS . Remove ?
    sed -i 's~.*\<CONFIG_FEATURE_PREFER_APPLETS\>.*~CONFIG_FEATURE_PREFER_APPLETS=y~' .config
    sed -i 's~.*\<CONFIG_FEATURE_SH_STANDALONE\>.*~CONFIG_FEATURE_SH_STANDALONE=y~' .config
    #
    cp .config .config.mod
    make
    strip busybox
    cp "$DIR_BUILD/busybox-master/busybox" "$RELEASE_FOLDER"/
    touch "$DIR_BUILD/busybox.built"
  fi
  cd "$DIR_CONTAINER"

  PACKNAME="libcap"
  cd "$DIR_BUILD"
  if [ ! -f "$DIR_BUILD/$PACKNAME.downloaded" ]; then
    download tmp.zip https://github.com/mhiramat/libcap/archive/refs/heads/master.zip
    unzip tmp.zip
    rm tmp.zip
    touch "$DIR_BUILD/$PACKNAME.downloaded"
  fi
  cd "$DIR_BUILD/libcap-master"
  if [ ! -f "$DIR_BUILD/$PACKNAME.built" ]; then
    make
    touch "$DIR_BUILD/$PACKNAME.built"
  fi

  PACKNAME="bubblewrap"
  cd "$DIR_BUILD"
  if [ ! -f "$DIR_BUILD/$PACKNAME.downloaded" ]; then
    download tmp.zip https://github.com/containers/bubblewrap/archive/refs/heads/main.zip
    unzip tmp.zip
    rm tmp.zip
    touch "$DIR_BUILD/$PACKNAME.downloaded"
  fi
  cd "$DIR_BUILD/bubblewrap-main"
  if [ ! -f "$DIR_BUILD/$PACKNAME.built" ]; then
    ##sed -i 's/, libcap_dep//' meson.build
    ##sed -i 's/^libcap_dep =.*//' meson.build
    #meson _builddir
    #meson compile -C _builddir
    VERSION="$(grep bubblewrap -A 5 meson.build | sed -n "s/.*\<version\>[\t ]*:[\t ]*'\([^']*\)'.*/\1/p")"
    cat > "config.h" << EOF
// Automatically generated by build script
#pragma once
#define ENABLE_REQUIRE_USERNS 1
#define PACKAGE_STRING "bubblewrap $VERSION"
#define _GNU_SOURCE # added for setns
#include <sched.h> # added for setns
EOF
    ${CC} -static -o bwrap -I "$DIR_BUILD/libcap-master/libcap/include" *c "$DIR_BUILD/libcap-master/libcap/libcap.a"
    strip bwrap
    cp "$DIR_BUILD/bubblewrap-main/bwrap" "$RELEASE_FOLDER"/
    touch "$DIR_BUILD/$PACKNAME.built"
  fi

  touch "$RELEASE_FOLDER"/container.done
  cp "$SRC_DIR"/corun.sh "$RELEASE_FOLDER"/
  cd "$CONTAINER_FOLDER"
  tar -czf ../container.tar.gz .
  cd -
}

main(){

  set -ex
  SRC_DIR="$(readlink -f "$(dirname "$0")")"
  DIR_BUILD="$SRC_DIR/cache/build"
  CONTAINER_FOLDER="$DIR_BUILD/container"
  RELEASE_FOLDER="$CONTAINER_FOLDER/coresys"
  make_all
}

main

